In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt


In [3]:

train_data= pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")
test_data =pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")
target = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/gender_submission.csv")


In [4]:
target = target["Survived"]
t=np.array(target)
t=t.T
t.shape

(418,)

In [5]:
A=[1,20,0,0,7.5]
S=[0,19,1,1,512]
ar=np.array(A)
sh=np.array(S)
ar=ar.reshape(5,1)
sh=sh.reshape(5,1)
ar.shape

(5, 1)

In [6]:
wa=np.full((ar.shape[0],1),0.01)
ws=np.full((sh.shape[0],1),0.01)
wa

array([[0.01],
       [0.01],
       [0.01],
       [0.01],
       [0.01]])

In [7]:
ws

array([[0.01],
       [0.01],
       [0.01],
       [0.01],
       [0.01]])

In [8]:
train_data
train_data['Age'].fillna(train_data['Age'].mean(), inplace=True)

In [9]:
ytrain=train_data["Survived"]
xtrain=train_data.drop(["Pclass","Cabin","Embarked","Name","Ticket","PassengerId"],axis=1)
xtest=test_data.drop(["Pclass","Cabin","Embarked","Name","Ticket","PassengerId"],axis=1)
xtest

Survived     Sex   Age  SibSp  Parch     Fare
0           0    male  22.0      1      0   7.2500
1           1  female  38.0      1      0  71.2833
2           1  female  26.0      0      0   7.9250
3           1  female  35.0      1      0  53.1000
4           0    male  35.0      0      0   8.0500
..        ...     ...   ...    ...    ...      ...
886         0    male  27.0      0      0  13.0000
887         1  female  19.0      0      0  30.0000
888         0  female   NaN      1      2  23.4500
889         1    male  26.0      0      0  30.0000
890         0    male  32.0      0      0   7.7500

[891 rows x 6 columns]

In [10]:

xtrain["Sex"].unique()
Gender={"male":1, "female":0}
xtrain=xtrain.replace(Gender)
xtest=xtest.replace(Gender)
xtrain

Survived  Sex        Age  SibSp  Parch     Fare
0           0    1  22.000000      1      0   7.2500
1           1    0  38.000000      1      0  71.2833
2           1    0  26.000000      0      0   7.9250
3           1    0  35.000000      1      0  53.1000
4           0    1  35.000000      0      0   8.0500
..        ...  ...        ...    ...    ...      ...
886         0    1  27.000000      0      0  13.0000
887         1    0  19.000000      0      0  30.0000
888         0    0  29.699118      1      2  23.4500
889         1    1  26.000000      0      0  30.0000
890         0    1  32.000000      0      0   7.7500

[891 rows x 6 columns]

In [11]:

def sigmoid(z):
    s = 1/(1 + np.exp(-z)) 
    # s[np.isnan(s)] = np.nanmean(s)
    return s

In [12]:
def loss(h,y):
  return(-(y*np.log(h)+(1-y)*np.log(1-h)))

In [13]:
def val(w,x,b):
  c=np.dot(w.T,x)+b
  c[np.isnan(c)] = np.nanmean(c)
  return c

In [14]:

def gradient(x,h,y):
  return (np.dot(x,(h-y).T)/x.shape[1])

In [15]:
def const(h,y):
   n=(np.sum(h-y))/x.shape[1]
   return n

In [16]:
def fit(x,lr,iter,w,b,y):
  for i in range(iter):
    z=val(w,x,b)
   
    # z=np.nan_to_num(z, nan=np.nanmean(z))
    a=sigmoid(z)
  
    # a=np.nan_to_num(a, nan=np.nanmean(a))
    los=loss(a,y)
    
    # los=np.nan_to_num(los, nan=np.nanmean(los))
    cost=(np.sum(los))/x.shape[1]
    dz=np.dot(a,y)
    
    dw=gradient(x,a,y)
   
    db=const(a,y)
    
    w=w-lr*dw
    w[np.isnan(w)] = np.nanmean(w)
    b=b-lr*db
    
    if (i%5==0):
      print ("Cost after iteration %i: %f" %(i, cost))
 

In [17]:
xtrain = (xtrain - np.min(xtrain)) / (np.max(xtrain) - np.min(xtrain)).values
xtest=(xtest - np.min(xtest)) / (np.max(xtest) - np.min(xtest)).values

In [18]:
x=np.array(xtrain)
x=x.T
x.shape


(6, 891)

In [19]:
xt=np.array(xtest)
xt=xt.T
xt.shape

(6, 891)

In [20]:
y=np.array(ytrain)
y=y.T
y.shape
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [21]:
w = np.full((x.shape[0],1),0.01)
w.shape

(6, 1)

In [22]:
wt = np.full((xt.shape[0],1),0.01)
wt.shape

(6, 1)

In [23]:
b=0.0

In [24]:
fit(x,0.0001,1000,w,b,y)

Cost after iteration 0: 0.693832
Cost after iteration 5: 0.693785
Cost after iteration 10: 0.693737
Cost after iteration 15: 0.693690
Cost after iteration 20: 0.693643
Cost after iteration 25: 0.693595
Cost after iteration 30: 0.693548
Cost after iteration 35: 0.693500
Cost after iteration 40: 0.693453
Cost after iteration 45: 0.693406
Cost after iteration 50: 0.693358
Cost after iteration 55: 0.693311
Cost after iteration 60: 0.693264
Cost after iteration 65: 0.693216
Cost after iteration 70: 0.693169
Cost after iteration 75: 0.693122
Cost after iteration 80: 0.693074
Cost after iteration 85: 0.693027
Cost after iteration 90: 0.692980
Cost after iteration 95: 0.692932
Cost after iteration 100: 0.692885
Cost after iteration 105: 0.692838
Cost after iteration 110: 0.692790
Cost after iteration 115: 0.692743
Cost after iteration 120: 0.692696
Cost after iteration 125: 0.692649
Cost after iteration 130: 0.692602
Cost after iteration 135: 0.692554
Cost after iteration 140: 0.692507
Cost af

In [25]:
def predict(w,b,x_test):
    # x_test is a input for forward propagation
    z = sigmoid(np.dot(w.T,x_test)+b)
    Y_prediction = np.zeros((1,x_test.shape[1]))
    # if z is bigger than 0.5, our prediction is one means has diabete (y_head=1),
    # if z is smaller than 0.5, our prediction is zero means does not have diabete (y_head=0),
    for i in range(z.shape[1]):
        if z[0,i]< 0.60:
            Y_prediction[0,i] = 0
        else:
            Y_prediction[0,i] = 1

    return Y_prediction

In [26]:
print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction - t)) * 100))

NameError: ignored

In [27]:
ypreda=predict(wa,b,ar)
if(ypreda):
  print("Arpit Survived")
else:
  print("Arpit Not Survived")

Arpit Not Survived


In [28]:
ypreds=predict(ws,b,sh)
if(ypreds):
  print("Shreya Survived")
else:
  print("Shreya Not Survived")

Shreya Survived
