## Checking the time taken by numpy library and loops

#### Initializing matrices and importing modules
- importing time and numpy module for time calculation and matrix operations respectively.

In [5]:
import time as T
import numpy as np
raw_1=np.random.randint(10, size=(10,10))
raw_2=np.random.randint(10, size=(10,10))
array_1=np.array(raw_1)
array_2=np.array(raw_2)
add=np.zeros((10,10))

#### addition
- In addition we simply applied element by element loop in our looping process 

In [6]:
#using loops
start1=T.time()
for i in range(len(raw_1)):
   for j in range(len(raw_1)):
       add[i][j] = raw_1[i][j] + raw_2[i][j]

end1=T.time()
print(add)
#using numpy
start2=T.time()
nadd=np.add(raw_1,raw_2)
end2=T.time()
print(nadd)

[[12. 17.  8. 12.  9.  4.  8.  8.  1. 13.]
 [ 4.  5. 10.  6.  9.  9.  6.  8.  4. 13.]
 [12.  6.  7.  8.  6. 17.  7. 10. 12. 17.]
 [16. 10. 15. 11. 14. 10.  6.  2. 13. 11.]
 [11.  2. 15.  4. 10.  6.  9. 10.  6. 11.]
 [ 6.  3.  9. 12.  9. 15. 14. 13.  4.  7.]
 [10. 12. 16. 13. 15.  6.  2. 14.  9.  5.]
 [10.  9.  6.  9.  8.  4. 10. 18. 10.  8.]
 [10.  9.  5. 13.  9. 10. 12. 11. 12.  8.]
 [ 9. 10.  7. 11.  4.  9.  9.  6. 13. 12.]]
[[12 17  8 12  9  4  8  8  1 13]
 [ 4  5 10  6  9  9  6  8  4 13]
 [12  6  7  8  6 17  7 10 12 17]
 [16 10 15 11 14 10  6  2 13 11]
 [11  2 15  4 10  6  9 10  6 11]
 [ 6  3  9 12  9 15 14 13  4  7]
 [10 12 16 13 15  6  2 14  9  5]
 [10  9  6  9  8  4 10 18 10  8]
 [10  9  5 13  9 10 12 11 12  8]
 [ 9 10  7 11  4  9  9  6 13 12]]


#### multiplication
- In looping process here we applied row wise an coloumn wise loops.

In [7]:
multiply=np.zeros((10,10))
#using loops
start3=T.time()
for i in range(len(raw_1)):
   for j in range(len(raw_1)):
       for k in range(len(raw_2)):
           multiply[i][j] += raw_1[i][k] * raw_2[k][j]
end3=T.time()
print(multiply)

#using numpy
start4=T.time()
nmultiply=np.matmul(array_1,array_2)
end4=T.time()
print(nmultiply)

[[306. 268. 351. 199. 276. 176. 135. 266. 259. 309.]
 [208. 121. 216. 152. 195. 186. 143. 200. 149. 154.]
 [244. 166. 240. 193. 223. 228. 169. 248. 191. 204.]
 [339. 209. 377. 224. 318. 246. 220. 303. 264. 269.]
 [261. 154. 204. 149. 170. 197. 123. 215. 192. 235.]
 [273. 169. 242. 169. 221. 210. 145. 249. 222. 209.]
 [313. 151. 256. 153. 198. 202. 141. 221. 228. 268.]
 [301. 235. 223. 150. 188. 185. 156. 263. 245. 210.]
 [254. 187. 229. 164. 183. 187. 158. 192. 198. 190.]
 [258. 264. 269. 209. 250. 204. 158. 297. 233. 230.]]
[[306 268 351 199 276 176 135 266 259 309]
 [208 121 216 152 195 186 143 200 149 154]
 [244 166 240 193 223 228 169 248 191 204]
 [339 209 377 224 318 246 220 303 264 269]
 [261 154 204 149 170 197 123 215 192 235]
 [273 169 242 169 221 210 145 249 222 209]
 [313 151 256 153 198 202 141 221 228 268]
 [301 235 223 150 188 185 156 263 245 210]
 [254 187 229 164 183 187 158 192 198 190]
 [258 264 269 209 250 204 158 297 233 230]]


#### Inverse
- In inverse here we applied jordan elimination and row operations simultaneously for matrix and a identity matrix.

In [8]:
#using numpy
start5=T.time()
ninv=np.linalg.inv(array_1)
end5=T.time()
print('inverse of matrix using numpy lib')
print(ninv)

#using loops
def invert_matrix(BC):
    n = len(BC)
    I=np.identity(n)
    indices = list(range(n))
    for fd in range(n):
        diagScaler = 1.0 / BC[fd][fd] 
        for j in range(n):
            BC[fd][j] *= diagScaler
            I[fd][j] *= diagScaler
        for i in indices[0:fd] + indices[fd+1:]: 
            ro_op = BC[i][fd]
            for j in range(n): 
                BC[i][j] = BC[i][j] - ro_op * BC[fd][j]
                I[i][j] = I[i][j] - ro_op * I[fd][j]
    return print("inverse of matrix using loop\n",I)
start6=T.time()
invert_matrix(raw_1)
end6=T.time()

inverse of matrix using numpy lib
[[-0.01355815  0.26690845 -0.32108845 -0.04596287  0.09074085 -0.1034031
   0.01683752 -0.09581953  0.13261702  0.15500515]
 [ 0.09779972 -0.17721754  0.41862651  0.01528583 -0.15740204 -0.12860606
   0.06639885  0.11557727 -0.20521119 -0.10716589]
 [-0.24373422 -0.06381886 -0.54395217  0.25793193  0.51690929  0.11018495
  -0.16235356 -0.21745673  0.10655638  0.25718761]
 [-0.04572141  0.00756351 -0.29229787  0.03815162  0.0321796   0.18454342
   0.03215544 -0.13605575  0.11330839  0.0896643 ]
 [ 0.11684846 -0.13913831  0.40914473  0.01601251 -0.20577558 -0.06284867
   0.01172856  0.18822456 -0.10008966 -0.26788048]
 [ 0.17265095  0.21339729  0.57995631 -0.28568144 -0.51873736 -0.16529008
   0.24514117  0.248347   -0.19396099 -0.22706226]
 [-0.18309615 -0.0249571  -0.64960931  0.27237238  0.47643234  0.21475214
  -0.30448945 -0.19626107  0.16146406  0.24333592]
 [ 0.22629147  0.09557932  0.66039149 -0.3612962  -0.49498126 -0.21103179
   0.27884802  0.3

In [9]:
pro3=end3-start3
pro4=end4-start4
pro5=end5-start5
pro6=end6-start6
print(f"""addition => loop time={end1-start1}, numpy time={end2-start2}
multiply => loop time={end3-start3}, numpy time={end4-start4}
inverse  => loop time={end6-start6}, numpy time={end5-start5}""")

addition => loop time=0.00029277801513671875, numpy time=0.00010657310485839844
multiply => loop time=0.0037202835083007812, numpy time=0.00028395652770996094
inverse  => loop time=0.015828371047973633, numpy time=0.0023136138916015625


#### Conclusion
- As from above we can see that numpy does matrix operations faster than traditional looping process